### ISSUE TITLE
Não consigo executar o projeto

### ISSUE THREAD

**Issue by manoger** [marcelomrwin/codigo-fonte-camel-quarkus#1]
Olá 👋
Eu estou tentando seguir o passo-a-passo do [video da casa do código](https://www.youtube.com/watch?v=oo0QGOVQYBI), no entanto não estou tendo exito em buildar e rodar o projeto AS-IS da master via `./mvnw quarkus:dev` ou `mvn clean quarkus:dev`.
Poderia dar uma olhada?

### O erro que estou tomando é
> **mvn clean quarkus:dev**
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'build.plugins.plugin.version' for io.quarkus:quarkus-maven-plugin must be a valid version but is '${quarkus.version}'. @ line 126, column 14

Se eu coloco a versão 1.9.1.Final
> [ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.9.1.Final:dev (default-cli) on project camel-codigo-fonte: Fatal error compiling: invalid target release: 11 -> [Help 1]

### Meu setup:

> **mvn --version**
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: C:\Program Files\Maven\apache-maven-3.9.6
Java version: 1.8.0_311, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_311\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

>**java --version**
openjdk 21.0.3 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)

**Comment by manoger** [comment]
Achei uma solução de contorno ao malfuncionamento da extensão maven usando o plugin quarkus.
Nessa [página](https://pt.quarkus.io/guides/maven-tooling) eu descobri que há alternativa de instalar via chocolatey `choco install quarkus --force` o utilitário quarkus CLI.
Ao invés de `./mvnw quarkus:dev` ou `mvn clean quarkus:dev` estou usando `quarkus dev`

**Comment by marcelomrwin** [comment]
> Olá 👋 Eu estou tentando seguir o passo-a-passo do [video da casa do código](https://www.youtube.com/watch?v=oo0QGOVQYBI), no entanto não estou tendo exito em buildar e rodar o projeto AS-IS da master via `./mvnw quarkus:dev` ou `mvn clean quarkus:dev`. Poderia dar uma olhada?
> 
> ### O erro que estou tomando é
> > **mvn clean quarkus:dev**
> > [INFO] Scanning for projects...
> > [ERROR] [ERROR] Some problems were encountered while processing the POMs:
> > [ERROR] 'build.plugins.plugin.version' for io.quarkus:quarkus-maven-plugin must be a valid version but is '${quarkus.version}'. @ line 126, column 14
> 
> Se eu coloco a versão 1.9.1.Final
> 
> > [ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.9.1.Final:dev (default-cli) on project camel-codigo-fonte: Fatal error compiling: invalid target release: 11 -> [Help 1]
> 
> ### Meu setup:
> > **mvn --version**
> > Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
> > Maven home: C:\Program Files\Maven\apache-maven-3.9.6
> > Java version: 1.8.0_311, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_311\jre
> > Default locale: en_US, platform encoding: Cp1252
> > OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
> 
> > **java --version**
> > openjdk 21.0.3 2024-04-16 LTS
> > OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
> > OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)

Oi @manoger. Fico feliz que tenha experimentado o projeto. 

Há algumas coisas que você precisa corrigir no seu ambiente ademais da correção no projeto.

Primeiramente precisar corrigir tua instalação de maven. Veja que no seu comando mvn --version estás usando a versão 3.9.6 e a JDK que o maven está utilizando é a 1.8. Este projeto exige no mínimo versão 11 para compilar.

Não importa que tenhas a JDK 21 como default, se o maven que tens está configurado para apontar para uma JDK 8 não vais conseguir compilar o projeto.

**Comment by marcelomrwin** [comment]
> Achei uma solução de contorno ao malfuncionamento da extensão maven usando o plugin quarkus. Nessa [página](https://pt.quarkus.io/guides/maven-tooling) eu descobri que há alternativa de instalar via chocolatey `choco install quarkus --force` o utilitário quarkus CLI. Ao invés de `./mvnw quarkus:dev` ou `mvn clean quarkus:dev` estou usando `quarkus dev`

Na verdade, se vc ler o erro vai perceber que a solução é bem mais simples. Bastava editar o pom.xml e substituir a linha 125 e trocar o nome da variável que faz referência a versão do quarkus. Trocar o nome de quarkus.version para quarkus.platform.version. Apenas isso seria suficiente para fazer o projeto compilar e executar. Eu fiz esta correção, obrigado por apontar.
